import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import {
  BadgeCheck,
  Code2,
  Download,
  FileSearch,
  FileText,
  Globe,
  Link2,
  ListChecks,
  MonitorDot,
  Radar,
  Rss,
  ScanText,
  ScrollText,
  Share2,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type RouteItem = {
  title: string;
  description: string;
  path: string;
  href: string;
  linkLabel: string;
  icon: LucideIcon;
};

const highlights = [
  {
    title: "Claim extraction",
    description: "Turn drafts or URLs into verifiable claims with source context.",
    icon: ScanText,
  },
  {
    title: "PoI agreement",
    description: "Run redundant router verifiers and measure dispersion.",
    icon: ListChecks,
  },
  {
    title: "PoUW rubric",
    description: "Grade quality with deterministic checks and rubric insights.",
    icon: ShieldCheck,
  },
  {
    title: "Proof artifacts",
    description: "Seals, badges, embeds, and downloadable evidence bundles.",
    icon: BadgeCheck,
  },
];

const coreRoutes = [
  {
    title: "Try a claim check",
    description: "Paste draft content and run redundant verification.",
    href: "/try",
    path: "/try",
    icon: Sparkles,
  },
  {
    title: "Audit a public URL",
    description: "Fetch sources, extract claims, and cite evidence.",
    href: "/audit",
    path: "/audit",
    icon: Globe,
  },
  {
    title: "Validate a single claim",
    description: "Mint a seal directly from a URL + claim pair.",
    href: "/validate",
    path: "/validate",
    icon: BadgeCheck,
  },
  {
    title: "Seal directory",
    description: "Browse public seals, badges, and embeds.",
    href: "/directory",
    path: "/directory",
    icon: ShieldCheck,
  },
  {
    title: "Monitor workspace",
    description: "Track RSS feeds and router health checks.",
    href: "/monitors",
    path: "/monitors",
    icon: Radar,
  },
  {
    title: "Create a monitor",
    description: "Schedule an RSS or router monitor.",
    href: "/monitors/new",
    path: "/monitors/new",
    icon: Rss,
  },
];

const routeGroups: Array<{
  title: string;
  description: string;
  items: RouteItem[];
}> = [
  {
    title: "Result + public pages",
    description: "Every shareable page generated by a run or monitor.",
    items: [
      {
        title: "Try results",
        description: "Analysis summary, claims, and proof generator.",
        path: "/try/results/[id]",
        href: "/try",
        linkLabel: "Go to Try",
        icon: FileText,
      },
      {
        title: "Audit results",
        description: "Source-backed audit with evidence quotes.",
        path: "/audit/results/[id]",
        href: "/audit",
        linkLabel: "Go to Audit",
        icon: FileSearch,
      },
      {
        title: "Monitor detail",
        description: "Run history, seal outputs, and health checks.",
        path: "/monitors/[id]",
        href: "/monitors",
        linkLabel: "View Monitors",
        icon: MonitorDot,
      },
      {
        title: "Seal public page",
        description: "Verdict view with evidence and share tools.",
        path: "/seal/[publicId]",
        href: "/directory",
        linkLabel: "Open Directory",
        icon: BadgeCheck,
      },
      {
        title: "Embed card",
        description: "Iframe-friendly badge card for embeds.",
        path: "/embed/[publicId]",
        href: "/directory",
        linkLabel: "Open Directory",
        icon: Link2,
      },
      {
        title: "Proof share page",
        description: "Public proof bundle view and download.",
        path: "/share/[id]",
        href: "/try",
        linkLabel: "Run a Check",
        icon: Share2,
      },
    ],
  },
  {
    title: "API + downloads",
    description: "Programmatic access to validators and bundles.",
    items: [
      {
        title: "Validation API",
        description: "Public POST validator with seal minting.",
        path: "/api/validate",
        href: "/api/openapi.json",
        linkLabel: "OpenAPI",
        icon: Code2,
      },
      {
        title: "OpenAPI schema",
        description: "Reference for all public endpoints.",
        path: "/api/openapi.json",
        href: "/api/openapi.json",
        linkLabel: "OpenAPI",
        icon: ScrollText,
      },
      {
        title: "Analysis evidence bundle",
        description: "Raw analysis snapshot download.",
        path: "/api/analyses/[id]/evidence",
        href: "/api/openapi.json",
        linkLabel: "OpenAPI",
        icon: Download,
      },
      {
        title: "Analysis proof bundle",
        description: "Proof export for analysis runs.",
        path: "/api/analyses/[id]/proof",
        href: "/api/openapi.json",
        linkLabel: "OpenAPI",
        icon: Download,
      },
      {
        title: "Seal bundle",
        description: "Download seal JSON data by public ID.",
        path: "/api/seals/[publicId]",
        href: "/api/openapi.json",
        linkLabel: "OpenAPI",
        icon: Download,
      },
      {
        title: "Badge SVG",
        description: "Inline badge asset for embeds.",
        path: "/api/badge/[publicId].svg",
        href: "/api/openapi.json",
        linkLabel: "OpenAPI",
        icon: BadgeCheck,
      },
      {
        title: "Immutable proof bundle",
        description: "Download a sealed proof bundle by ID.",
        path: "/api/proofs/[id]",
        href: "/api/openapi.json",
        linkLabel: "OpenAPI",
        icon: Download,
      },
    ],
  },
];

export default function Home() {
  return (
    <div className="mx-auto w-full max-w-6xl px-6 pb-24 pt-12">
      <section className="relative grid items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]">
        <div className="space-y-6 animate-rise">
          <div className="flex flex-wrap items-center gap-3">
            <Badge
              variant="outline"
              className="flex items-center gap-2 border-primary/30 bg-background/70 text-foreground"
            >
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              Decentralized trust for creators
            </Badge>
            <span className="text-xs uppercase tracking-[0.35em] text-muted-foreground">
              Cortensor Router
            </span>
          </div>
          <h1 className="font-display text-balance text-4xl leading-tight md:text-6xl">
            The{" "}
            <span className="bg-gradient-to-r from-primary via-indigo-500 to-accent bg-clip-text text-transparent">
              proof layer
            </span>{" "}
            for claims, audits, and public sources.
          </h1>
          <p className="max-w-xl text-pretty text-lg text-muted-foreground">
            CortSeal extracts verifiable claims, runs redundant router checks (PoI), applies a
            PoUW rubric, and publishes seals, badges, embeds, and evidence bundles you can share.
          </p>
          <div className="flex flex-wrap gap-3">
            <Button
              asChild
              size="lg"
              className="bg-gradient-to-r from-primary via-indigo-500 to-primary text-primary-foreground shadow-sm transition hover:opacity-90"
            >
              <Link href="/try">Start a check</Link>
            </Button>
            <Button asChild size="lg" variant="secondary">
              <Link href="/audit">Audit a URL</Link>
            </Button>
            <Button asChild size="lg" variant="outline">
              <Link href="/validate">Mint a seal</Link>
            </Button>
            <Button asChild size="lg" variant="ghost">
              <Link href="/api/openapi.json">OpenAPI</Link>
            </Button>
          </div>
          <div className="flex flex-wrap gap-2 text-xs text-muted-foreground">
            <Badge variant="secondary" className="border border-border/60">
              PoI redundancy
            </Badge>
            <Badge variant="secondary" className="border border-border/60">
              PoUW scoring
            </Badge>
            <Badge variant="secondary" className="border border-border/60">
              Evidence bundles
            </Badge>
            <Badge variant="secondary" className="border border-border/60">
              Public proofs
            </Badge>
          </div>
        </div>

        <div className="relative space-y-6 animate-rise" style={{ animationDelay: "120ms" }}>
          <Card className="relative overflow-hidden border-border/60 bg-card/80 backdrop-blur">
            <div aria-hidden="true" className="absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-accent/10" />
            <CardHeader className="relative">
              <Badge variant="outline" className="w-fit border-border/60 bg-card/70">
                Proof snapshot
              </Badge>
              <CardTitle className="text-2xl">From claim to seal in minutes.</CardTitle>
              <CardDescription>
                A single run produces consensus verdicts, a rubric score, and shareable artifacts.
              </CardDescription>
            </CardHeader>
            <CardContent className="relative space-y-4 text-sm">
              <div className="grid gap-3 sm:grid-cols-2">
                {highlights.map((item) => (
                  <div
                    key={item.title}
                    className="flex items-start gap-3 rounded-2xl border border-border/60 bg-background/80 p-3"
                  >
                    <span className="flex h-9 w-9 items-center justify-center rounded-2xl border border-border/60 bg-background/80">
                      <item.icon className="h-4 w-4 text-primary" />
                    </span>
                    <div>
                      <p className="text-sm font-semibold">{item.title}</p>
                      <p className="text-xs text-muted-foreground">{item.description}</p>
                    </div>
                  </div>
                ))}
              </div>
              <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                <Badge variant="outline">SUPPORTED · 92%</Badge>
                <span>Dispersion 0.12 · Runs 3x</span>
              </div>
            </CardContent>
          </Card>

          <Card className="border-border/60 bg-card/80 backdrop-blur">
            <CardHeader>
              <CardTitle className="text-lg">Proof artifacts</CardTitle>
              <CardDescription>Ship seals, embeds, and proof bundles.</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3 text-sm sm:grid-cols-2">
              <div className="rounded-2xl border border-border/60 bg-background/80 p-3">
                <p className="text-xs text-muted-foreground">Public seal</p>
                <p className="mt-1 font-medium">/seal/[publicId]</p>
              </div>
              <div className="rounded-2xl border border-border/60 bg-background/80 p-3">
                <p className="text-xs text-muted-foreground">Embed card</p>
                <p className="mt-1 font-medium">/embed/[publicId]</p>
              </div>
              <div className="rounded-2xl border border-border/60 bg-background/80 p-3">
                <p className="text-xs text-muted-foreground">Proof bundle</p>
                <p className="mt-1 font-medium">/api/proofs/[id]</p>
              </div>
              <div className="rounded-2xl border border-border/60 bg-background/80 p-3">
                <p className="text-xs text-muted-foreground">Evidence JSON</p>
                <p className="mt-1 font-medium">/api/analyses/[id]/evidence</p>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>

      <section className="mt-20 space-y-6">
        <div className="space-y-2">
          <p className="text-xs uppercase tracking-[0.35em] text-muted-foreground">Core routes</p>
          <h2 className="font-display text-3xl">Every workflow, one click away</h2>
          <p className="text-muted-foreground">
            Navigate directly to every primary page with clear explanations and links.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {coreRoutes.map((route) => (
            <Link key={route.title} href={route.href} className="group">
              <Card className="h-full border-border/60 bg-card/80 transition hover:-translate-y-1 hover:shadow-lg">
                <CardHeader className="space-y-4">
                  <span className="flex h-12 w-12 items-center justify-center rounded-2xl border border-border/60 bg-background/80">
                    <route.icon className="h-5 w-5 text-primary" />
                  </span>
                  <div className="space-y-2">
                    <CardTitle className="text-lg">{route.title}</CardTitle>
                    <CardDescription>{route.description}</CardDescription>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-xs font-mono text-muted-foreground">{route.path}</p>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-20 space-y-6">
        <div className="space-y-2">
          <p className="text-xs uppercase tracking-[0.35em] text-muted-foreground">Route atlas</p>
          <h2 className="font-display text-3xl">All pages + endpoints, fully mapped</h2>
          <p className="text-muted-foreground">
            Every dynamic view and download route is included below with its source path.
          </p>
        </div>
        <div className="grid gap-6 lg:grid-cols-2">
          {routeGroups.map((group) => (
            <Card key={group.title} className="border-border/60 bg-card/80">
              <CardHeader>
                <CardTitle className="text-xl">{group.title}</CardTitle>
                <CardDescription>{group.description}</CardDescription>
              </CardHeader>
              <CardContent className="grid gap-3">
                {group.items.map((item) => (
                  <Link
                    key={item.title}
                    href={item.href}
                    className="group flex items-start gap-3 rounded-2xl border border-border/60 bg-background/80 p-3 transition hover:border-primary/40"
                  >
                    <span className="flex h-9 w-9 items-center justify-center rounded-xl border border-border/60 bg-background/80">
                      <item.icon className="h-4 w-4 text-primary" />
                    </span>
                    <div className="flex-1 space-y-1">
                      <div className="flex items-center justify-between gap-3">
                        <p className="text-sm font-semibold">{item.title}</p>
                        <span className="text-xs font-medium text-primary">{item.linkLabel}</span>
                      </div>
                      <p className="text-xs text-muted-foreground">{item.description}</p>
                      <p className="text-xs font-mono text-muted-foreground">{item.path}</p>
                    </div>
                  </Link>
                ))}
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <section className="mt-20">
        <Card className="border-border/60 bg-card/80 px-6 py-10 backdrop-blur">
          <div className="grid gap-6 md:grid-cols-[1.2fr_0.8fr] md:items-center">
            <div className="space-y-3">
              <h2 className="font-display text-3xl">Ready to seal your first claim?</h2>
              <p className="text-muted-foreground">
                Start with a draft or a public URL. CortSeal handles extraction, verification,
                evidence, and shareable proof delivery.
              </p>
            </div>
            <div className="flex flex-wrap gap-3">
              <Button
                asChild
                size="lg"
                className="bg-gradient-to-r from-primary via-indigo-500 to-primary text-primary-foreground shadow-sm transition hover:opacity-90"
              >
                <Link href="/try">Run a draft check</Link>
              </Button>
              <Button asChild size="lg" variant="secondary">
                <Link href="/audit">Audit a URL</Link>
              </Button>
              <Button asChild size="lg" variant="outline">
                <Link href="/directory">Explore seals</Link>
              </Button>
            </div>
          </div>
        </Card>
      </section>
    </div>
  );
}
